version: '3.8'

services:
  postgres:
    container_name: tp2-db 
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - ./.volumes/postgres/data:/var/lib/postgresql/data/
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: consultoriodb

  backend:
    container_name: tp2-backend
    build:
      context: ./server
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: consultoriodb
    ports:
      - "8080:8080"
    volumes:
      - ./server:/usr/src/app
    working_dir: /usr/src/app
    command: ["node", "index.js"]

  frontend:
    container_name: tp2-frontend
    image: nginx:alpine
    volumes:
      - ./client:/usr/share/nginx/html:ro
    ports:
      - "3000:80"
    depends_on:
      - backend